In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,RobustScaler
from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv('dataset_Facebook.csv')

In [3]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     500 non-null    int64
 1   Type                                                                 500 non-null    object
 2   Category                                                             500 non-null    int64
 3   Post Month                                                           500 non-null    int64
 4   Post Weekday                                                         500 non-null    int64
 5   Post Hour                                                            500 non-null    int64
 6   Paid                                                                 499 non-null    float64
 7   Lifetime Post Total Reach                                            500 non-null    int64
 8   Lifetime Post Total Impressions                                      500 non-null    int64
 9   Lifetime Engaged Users                                               500 non-null    int64
 10  Lifetime Post Consumers                                              500 non-null    int64
 11  Lifetime Post Consumptions                                           500 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 13  Lifetime Post reach by people who like your Page                     500 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 15  comment                                                              500 non-null    int64
 16  like                                                                 499 non-null    float64
 17  share                                                                496 non-null    float64
 18  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [5]:
df.dropna(inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 495 entries, 0 to 498
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     495 non-null    int64
 1   Type                                                                 495 non-null    object
 2   Category                                                             495 non-null    int64
 3   Post Month                                                           495 non-null    int64
 4   Post Weekday                                                         495 non-null    int64
 5   Post Hour                                                            495 non-null    int64
 6   Paid                                                                 495 non-null    float64
 7   Lifetime Post Total Reach                                            495 non-null    int64
 8   Lifetime Post Total Impressions                                      495 non-null    int64
 9   Lifetime Engaged Users                                               495 non-null    int64
 10  Lifetime Post Consumers                                              495 non-null    int64
 11  Lifetime Post Consumptions                                           495 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         495 non-null    int64
 13  Lifetime Post reach by people who like your Page                     495 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  495 non-null    int64
 15  comment                                                              495 non-null    int64
 16  like                                                                 495 non-null    float64
 17  share                                                                495 non-null    float64
 18  Total Interactions                                                   495 non-null    int64
dtypes: float64(3), int64(15), object(1)
memory usage: 77.3+ KB

In [7]:
le=LabelEncoder()
df['Type']=le.fit_transform(df['Type'])

In [8]:
rs=RobustScaler()

In [9]:
rs.fit_transform(df)

array([[ 0.40886618,  0.        ,  0.        , ..., -0.16793893,
        -0.08888889, -0.1572327 ],
       [ 0.40886618,  1.        ,  0.        , ...,  0.22137405,
         0.44444444,  0.24528302],
       [ 0.40886618,  0.        ,  0.5       , ..., -0.26717557,
        -0.22222222, -0.28301887],
       ...,
       [-2.00382234,  0.        ,  0.        , ..., -0.36641221,
         0.13333333, -0.31446541],
       [-2.00382234,  0.        , -0.5       , ..., -0.0610687 ,
        -0.04444444, -0.06289308],
       [-2.00382234,  0.        ,  0.5       , ..., -0.07633588,
         0.84444444,  0.06918239]])

In [10]:
scaled_df=pd.DataFrame(data=rs.fit_transform(df),columns=df.columns)

In [11]:
scaled_df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,0.408866,0.0,0.0,0.833333,0.00,-0.750,0.0,-0.255924,-0.239030,-0.681750,-0.703470,-0.726332,-0.289444,-0.316624,-0.822715,0.166667,-0.167939,-0.088889,-0.157233
1,0.408866,1.0,0.0,0.833333,-0.25,0.125,0.0,0.521327,0.597007,1.247360,1.271293,0.841180,0.490356,0.453747,1.916898,0.333333,0.221374,0.444444,0.245283
2,0.408866,0.0,0.5,0.833333,-0.25,-0.750,0.0,-0.290108,-0.282011,-0.683258,-0.697161,-0.731505,-0.313474,-0.340224,-0.786704,-0.500000,-0.267176,-0.222222,-0.283019
3,0.408866,0.0,0.0,0.833333,-0.50,0.125,1.0,4.521327,4.723556,2.384615,0.370662,0.266943,4.945571,4.921619,2.686981,9.166667,11.229008,5.688889,10.389937
4,0.408866,0.0,0.0,0.833333,-0.50,-0.750,0.0,0.197035,0.269979,0.061840,-0.228707,-0.290740,-0.004878,-0.047890,-0.055402,2.666667,1.709924,1.333333,1.685535

##  PCA

In [16]:
def custom_PCA(X):
    n_comp=len(X.columns)
    for i in range(1,n_comp):
        pca=PCA(n_components=i)
        p_comp=pca.fit_transform(X)
        evr=np.cumsum(pca.explained_variance_ratio_)
        print(evr)
        if evr[i-1]>0.9:
            pcs=i
            break
    print('Explained Variance Ratio after PCA is: ',evr)
    #Creating a dataframe of prinipal components
    col=[]
    for j in range(1,pcs+1):
        col.append('PC_'+str(j))
    pca_df=pd.DataFrame(p_comp,columns=col)
    return pca_df

In [17]:
pca_df=custom_PCA(scaled_df)

[0.56473733]
[0.56473733 0.7988726 ]
[0.56473733 0.7988726  0.87284714]
[0.56473733 0.7988726  0.87284714 0.9282212 ]
Explained Variance Ratio after PCA is:  [0.56473733 0.7988726  0.87284714 0.9282212 ]

In [ ]:
pca_df.head()

###  we are able to extract 90% of the information from the first four PCs,which means we hv reduced the feature count by 76% from 19 features to 4 features